insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (1, 'volutpat', 'dui maecenas tristique est et tempus semper', 87, 73, 8);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (2, 'dis parturient', 'nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus', 59, 151, 29);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (3, 'nulla nunc', 'ac leo', 6, 187, 10);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (4, 'pede', 'euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula', 73, 196, 16);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (5, 'cursus id', 'neque aenean', 14, 149, 6);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (6, 'rutrum', 'justo sit amet sapien dignissim vestibulum vestibulum ante ipsum', 13, 142, 29);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (7, 'vel', 'sed nisl nunc rhoncus dui vel sem sed', 6, 106, 28);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (8, 'cubilia', 'cursus urna ut tellus nulla ut erat', 67, 73, 19);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (9, 'eros elementum', 'eu tincidunt in', 10, 191, 24);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (10, 'sollicitudin mi', 'platea dictumst', 26, 87, 8);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (11, 'velit', 'nullam orci pede venenatis non', 84, 37, 25);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (12, 'quis', 'in congue', 75, 40, 7);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (13, 'vel sem', 'nam ultrices', 28, 66, 13);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (14, 'etiam', 'quis turpis sed ante vivamus tortor', 37, 147, 6);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (15, 'est et', 'est congue elementum in hac habitasse platea dictumst morbi vestibulum', 35, 85, 24);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (16, 'vehicula condimentum', 'lorem ipsum dolor sit amet consectetuer adipiscing', 23, 112, 17);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (17, 'eu', 'tempus vel', 23, 118, 17);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (18, 'justo aliquam', 'mus vivamus vestibulum sagittis sapien cum sociis', 9, 49, 5);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (19, 'nonummy', 'eget eros elementum pellentesque quisque porta volutpat erat', 57, 61, 6);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (20, 'purus sit', 'lorem vitae mattis nibh ligula', 85, 193, 29);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (21, 'nisl duis', 'quis odio consequat varius integer ac leo', 65, 34, 11);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (22, 'donec', 'vel nisl duis ac nibh fusce lacus', 13, 50, 15);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (23, 'ut ultrices', 'eget vulputate ut ultrices vel', 19, 89, 8);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (24, 'arcu', 'nunc rhoncus dui vel sem sed sagittis', 16, 157, 10);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (25, 'mauris', 'erat volutpat in congue etiam', 98, 112, 14);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (26, 'sapien', 'suspendisse ornare consequat lectus', 100, 52, 15);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (27, 'bibendum imperdiet', 'odio curabitur convallis duis consequat dui nec nisi volutpat eleifend', 67, 173, 24);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (28, 'dolor quis', 'velit nec nisi vulputate nonummy maecenas tincidunt lacus at', 50, 133, 11);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (29, 'curabitur', 'libero quis orci nullam molestie nibh in lectus', 73, 106, 21);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (30, 'proin', 'in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae', 76, 116, 23);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (31, 'ipsum', 'rutrum ac lobortis vel dapibus', 91, 32, 13);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (32, 'cubilia', 'elementum ligula', 13, 164, 17);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (33, 'at', 'elementum ligula vehicula consequat morbi a ipsum integer', 86, 94, 29);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (34, 'eget rutrum', 'libero nullam sit', 93, 113, 12);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (35, 'quis', 'cras mi pede malesuada', 17, 158, 25);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (36, 'tempus', 'morbi a ipsum integer a nibh', 71, 113, 17);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (37, 'primis in', 'morbi a ipsum integer a nibh in quis', 54, 191, 16);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (38, 'urna pretium', 'luctus cum', 46, 178, 16);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (39, 'faucibus', 'nibh in hac habitasse platea dictumst aliquam', 95, 199, 17);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (40, 'ut', 'iaculis congue vivamus', 69, 122, 13);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (41, 'erat', 'duis mattis egestas metus aenean fermentum donec ut', 45, 98, 13);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (42, 'lobortis', 'cras in purus eu magna', 16, 56, 19);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (43, 'rutrum', 'vitae mattis nibh ligula nec sem duis aliquam', 46, 147, 4);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (44, 'proin eu', 'augue quam sollicitudin vitae consectetuer eget rutrum', 70, 134, 13);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (45, 'odio elementum', 'vestibulum proin eu', 22, 61, 16);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (46, 'a odio', 'et ultrices posuere cubilia curae', 39, 166, 3);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (47, 'ipsum', 'orci vehicula', 80, 143, 5);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (48, 'ullamcorper', 'at turpis donec posuere metus vitae ipsum', 50, 193, 21);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (49, 'dui proin', 'dictumst maecenas ut massa quis augue luctus tincidunt', 91, 69, 9);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (50, 'eros', 'fusce lacus purus aliquet at feugiat non', 38, 67, 14);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (51, 'condimentum id', 'eget semper', 43, 119, 8);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (52, 'orci', 'ante ipsum', 87, 141, 2);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (53, 'pulvinar sed', 'cras mi pede malesuada in imperdiet et', 18, 133, 16);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (54, 'tincidunt in', 'nullam molestie nibh in lectus pellentesque', 95, 103, 16);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (55, 'in tempor', 'lacinia sapien', 66, 132, 24);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (56, 'dolor', 'luctus ultricies eu nibh quisque id justo sit amet', 96, 195, 13);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (57, 'ultrices enim', 'a feugiat et eros vestibulum ac est lacinia', 15, 173, 16);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (58, 'risus praesent', 'amet eleifend pede libero quis orci nullam', 74, 85, 19);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (59, 'at turpis', 'cum sociis', 38, 126, 21);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (60, 'tortor duis', 'est et tempus semper est quam pharetra magna', 17, 73, 2);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (61, 'purus', 'lectus vestibulum quam sapien varius ut', 100, 87, 29);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (62, 'tincidunt', 'quis turpis sed ante vivamus tortor duis mattis', 31, 71, 2);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (63, 'magna at', 'sed interdum venenatis turpis enim blandit mi in porttitor', 6, 91, 11);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (64, 'venenatis tristique', 'interdum mauris ullamcorper purus sit amet nulla', 12, 185, 17);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (65, 'id', 'convallis nulla neque', 96, 61, 24);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (66, 'pulvinar', 'volutpat quam pede lobortis', 48, 122, 13);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (67, 'venenatis tristique', 'convallis eget eleifend luctus ultricies eu', 61, 159, 4);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (68, 'suscipit', 'eu massa donec dapibus duis', 75, 166, 23);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (69, 'vel accumsan', 'quam suspendisse potenti nullam porttitor lacus at turpis', 75, 32, 16);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (70, 'tempus', 'mauris vulputate elementum nullam varius nulla facilisi cras non velit', 75, 167, 11);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (71, 'amet diam', 'sed justo pellentesque viverra', 50, 141, 26);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (72, 'ante', 'augue vel accumsan tellus', 85, 156, 29);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (73, 'vitae', 'suscipit ligula in lacus curabitur at ipsum ac tellus semper', 5, 60, 17);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (74, 'congue elementum', 'in sagittis dui vel nisl duis ac nibh fusce lacus', 45, 93, 12);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (75, 'morbi', 'molestie sed justo pellentesque', 34, 190, 15);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (76, 'hac', 'non interdum', 26, 140, 9);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (77, 'etiam vel', 'convallis morbi odio odio elementum eu interdum eu tincidunt', 76, 196, 5);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (78, 'odio', 'integer tincidunt ante vel', 25, 102, 27);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (79, 'orci mauris', 'fusce consequat nulla nisl nunc nisl duis', 74, 50, 2);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (80, 'posuere', 'sed tristique', 33, 131, 25);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (81, 'dolor', 'in porttitor pede justo eu massa donec dapibus duis', 9, 97, 23);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (82, 'in', 'pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit', 89, 116, 5);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (83, 'ultrices', 'odio cras mi pede malesuada in imperdiet', 78, 193, 30);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (84, 'sed lacus', 'odio odio elementum eu interdum eu tincidunt', 14, 94, 2);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (85, 'natoque penatibus', 'in porttitor pede justo eu massa donec dapibus duis at', 41, 53, 13);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (86, 'sapien varius', 'volutpat dui maecenas tristique est et tempus semper est', 80, 78, 12);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (87, 'at dolor', 'primis in faucibus orci luctus et ultrices posuere cubilia', 74, 115, 11);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (88, 'sem', 'consequat varius integer ac leo pellentesque', 28, 159, 17);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (89, 'diam', 'id pretium', 20, 79, 28);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (90, 'cubilia curae', 'arcu sed augue aliquam erat volutpat in', 45, 100, 30);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (91, 'in', 'leo rhoncus sed vestibulum sit amet cursus', 90, 64, 4);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (92, 'etiam', 'interdum venenatis turpis enim blandit mi in', 21, 119, 23);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (93, 'aliquam erat', 'pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas', 34, 171, 5);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (94, 'vestibulum quam', 'cum sociis natoque penatibus et magnis dis parturient montes nascetur', 8, 128, 5);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (95, 'in imperdiet', 'nibh in quis justo maecenas rhoncus aliquam lacus', 54, 143, 29);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (96, 'ipsum', 'sed tristique in', 90, 120, 11);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (97, 'pretium quis', 'vel nulla eget eros elementum pellentesque', 64, 188, 3);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (98, 'sit amet', 'vestibulum eget vulputate ut ultrices vel augue', 84, 77, 27);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (99, 'aliquet', 'curabitur gravida nisi at nibh in hac habitasse platea dictumst', 86, 179, 30);
insert into t_arme (id_arme, nom, description, prix, degat, coupMax) values (100, 'nisi volutpat', 'nulla eget', 28, 52, 5);
